version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: git_alarm_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=0000
      - MYSQL_DATABASE=git_alarm
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  git_alarm:
    image: joseongsik/myapp
    container_name: git_alarm
    ports:
      - "8086:8086"
    expose:
      - "8086"
