mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=0000
    - MYSQL_DATABASE=git_grass
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
